// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ganymede/zoo/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_52ec9e43a71a5d5e, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52ec9e43a71a5d5e, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetKvzooRequest struct {
	Owner  string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	ZooKey string `protobuf:"bytes,2,opt,name=zooKey,proto3" json:"zooKey,omitempty"`
}

func (m *QueryGetKvzooRequest) Reset()         { *m = QueryGetKvzooRequest{} }
func (m *QueryGetKvzooRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetKvzooRequest) ProtoMessage()    {}
func (*QueryGetKvzooRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_52ec9e43a71a5d5e, []int{2}
}
func (m *QueryGetKvzooRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetKvzooRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetKvzooRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetKvzooRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetKvzooRequest.Merge(m, src)
}
func (m *QueryGetKvzooRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetKvzooRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetKvzooRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetKvzooRequest proto.InternalMessageInfo

func (m *QueryGetKvzooRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *QueryGetKvzooRequest) GetZooKey() string {
	if m != nil {
		return m.ZooKey
	}
	return ""
}

type QueryGetKvzooResponse struct {
	Kvzoo Kvzoo `protobuf:"bytes,1,opt,name=kvzoo,proto3" json:"kvzoo"`
}

func (m *QueryGetKvzooResponse) Reset()         { *m = QueryGetKvzooResponse{} }
func (m *QueryGetKvzooResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetKvzooResponse) ProtoMessage()    {}
func (*QueryGetKvzooResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52ec9e43a71a5d5e, []int{3}
}
func (m *QueryGetKvzooResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetKvzooResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetKvzooResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetKvzooResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetKvzooResponse.Merge(m, src)
}
func (m *QueryGetKvzooResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetKvzooResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetKvzooResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetKvzooResponse proto.InternalMessageInfo

func (m *QueryGetKvzooResponse) GetKvzoo() Kvzoo {
	if m != nil {
		return m.Kvzoo
	}
	return Kvzoo{}
}

type QueryAllKvzooRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllKvzooRequest) Reset()         { *m = QueryAllKvzooRequest{} }
func (m *QueryAllKvzooRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllKvzooRequest) ProtoMessage()    {}
func (*QueryAllKvzooRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_52ec9e43a71a5d5e, []int{4}
}
func (m *QueryAllKvzooRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllKvzooRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllKvzooRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllKvzooRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllKvzooRequest.Merge(m, src)
}
func (m *QueryAllKvzooRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllKvzooRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllKvzooRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllKvzooRequest proto.InternalMessageInfo

func (m *QueryAllKvzooRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllKvzooResponse struct {
	Kvzoo      []Kvzoo             `protobuf:"bytes,1,rep,name=kvzoo,proto3" json:"kvzoo"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllKvzooResponse) Reset()         { *m = QueryAllKvzooResponse{} }
func (m *QueryAllKvzooResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllKvzooResponse) ProtoMessage()    {}
func (*QueryAllKvzooResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52ec9e43a71a5d5e, []int{5}
}
func (m *QueryAllKvzooResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllKvzooResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllKvzooResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllKvzooResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllKvzooResponse.Merge(m, src)
}
func (m *QueryAllKvzooResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllKvzooResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllKvzooResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllKvzooResponse proto.InternalMessageInfo

func (m *QueryAllKvzooResponse) GetKvzoo() []Kvzoo {
	if m != nil {
		return m.Kvzoo
	}
	return nil
}

func (m *QueryAllKvzooResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryListByOwnerRequest struct {
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Page  uint64 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit uint64 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (m *QueryListByOwnerRequest) Reset()         { *m = QueryListByOwnerRequest{} }
func (m *QueryListByOwnerRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListByOwnerRequest) ProtoMessage()    {}
func (*QueryListByOwnerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_52ec9e43a71a5d5e, []int{6}
}
func (m *QueryListByOwnerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListByOwnerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListByOwnerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListByOwnerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListByOwnerRequest.Merge(m, src)
}
func (m *QueryListByOwnerRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryListByOwnerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListByOwnerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListByOwnerRequest proto.InternalMessageInfo

func (m *QueryListByOwnerRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *QueryListByOwnerRequest) GetPage() uint64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *QueryListByOwnerRequest) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type QueryListByOwnerResponse struct {
	Kvzoo []*Kvzoo `protobuf:"bytes,1,rep,name=kvzoo,proto3" json:"kvzoo,omitempty"`
}

func (m *QueryListByOwnerResponse) Reset()         { *m = QueryListByOwnerResponse{} }
func (m *QueryListByOwnerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListByOwnerResponse) ProtoMessage()    {}
func (*QueryListByOwnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52ec9e43a71a5d5e, []int{7}
}
func (m *QueryListByOwnerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListByOwnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListByOwnerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListByOwnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListByOwnerResponse.Merge(m, src)
}
func (m *QueryListByOwnerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryListByOwnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListByOwnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListByOwnerResponse proto.InternalMessageInfo

func (m *QueryListByOwnerResponse) GetKvzoo() []*Kvzoo {
	if m != nil {
		return m.Kvzoo
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "ganymede.zoo.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "ganymede.zoo.QueryParamsResponse")
	proto.RegisterType((*QueryGetKvzooRequest)(nil), "ganymede.zoo.QueryGetKvzooRequest")
	proto.RegisterType((*QueryGetKvzooResponse)(nil), "ganymede.zoo.QueryGetKvzooResponse")
	proto.RegisterType((*QueryAllKvzooRequest)(nil), "ganymede.zoo.QueryAllKvzooRequest")
	proto.RegisterType((*QueryAllKvzooResponse)(nil), "ganymede.zoo.QueryAllKvzooResponse")
	proto.RegisterType((*QueryListByOwnerRequest)(nil), "ganymede.zoo.QueryListByOwnerRequest")
	proto.RegisterType((*QueryListByOwnerResponse)(nil), "ganymede.zoo.QueryListByOwnerResponse")
}

func init() { proto.RegisterFile("ganymede/zoo/query.proto", fileDescriptor_52ec9e43a71a5d5e) }

var fileDescriptor_52ec9e43a71a5d5e = []byte{
	// 610 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0x41, 0x6f, 0x12, 0x41,
	0x14, 0xc7, 0xd9, 0x16, 0x88, 0x4e, 0x3d, 0x4d, 0x51, 0x91, 0x98, 0x2d, 0x5d, 0x63, 0x5b, 0x4d,
	0xdc, 0xb1, 0x78, 0x31, 0x1e, 0x8c, 0x25, 0xda, 0x6a, 0x6a, 0x62, 0x25, 0x5e, 0xf4, 0x60, 0x33,
	0xd4, 0xc9, 0x66, 0xe3, 0xb2, 0x6f, 0xcb, 0x0c, 0xad, 0x0b, 0x72, 0xf1, 0xe8, 0x49, 0xe3, 0x57,
	0xf0, 0x13, 0xf8, 0x29, 0x7a, 0x6c, 0xe2, 0xc5, 0x93, 0x31, 0xe0, 0x07, 0x31, 0xfb, 0x66, 0x1a,
	0x58, 0xd8, 0x82, 0xb7, 0x9d, 0x99, 0xff, 0xfc, 0xff, 0xbf, 0xf7, 0xe6, 0x01, 0x29, 0x7b, 0x3c,
	0x8c, 0x5b, 0xe2, 0x9d, 0x60, 0x5d, 0x00, 0x76, 0xd8, 0x11, 0xed, 0xd8, 0x8d, 0xda, 0xa0, 0x80,
	0x5e, 0x3a, 0x3b, 0x71, 0xbb, 0x00, 0x95, 0x92, 0x07, 0x1e, 0xe0, 0x01, 0x4b, 0xbe, 0xb4, 0xa6,
	0x72, 0xdd, 0x03, 0xf0, 0x02, 0xc1, 0x78, 0xe4, 0x33, 0x1e, 0x86, 0xa0, 0xb8, 0xf2, 0x21, 0x94,
	0xe6, 0xf4, 0xf6, 0x01, 0xc8, 0x16, 0x48, 0xd6, 0xe4, 0x52, 0x68, 0x6b, 0x76, 0xb4, 0xd9, 0x14,
	0x8a, 0x6f, 0xb2, 0x88, 0x7b, 0x7e, 0x88, 0x62, 0xa3, 0xbd, 0x96, 0xe2, 0x88, 0x78, 0x9b, 0xb7,
	0xce, 0x6c, 0xd2, 0x88, 0xef, 0x8f, 0xba, 0x60, 0xe2, 0x9d, 0x12, 0xa1, 0x2f, 0x13, 0xdb, 0x3d,
	0x94, 0x37, 0xc4, 0x61, 0x47, 0x48, 0xe5, 0x3c, 0x23, 0xcb, 0xa9, 0x5d, 0x19, 0x41, 0x28, 0x05,
	0xad, 0x91, 0xa2, 0xb6, 0x2d, 0x5b, 0x55, 0x6b, 0x63, 0xa9, 0x56, 0x72, 0xc7, 0x0b, 0x74, 0xb5,
	0xba, 0x9e, 0x3f, 0xf9, 0xbd, 0x92, 0x6b, 0x18, 0xa5, 0xf3, 0x98, 0x94, 0xd0, 0x6a, 0x47, 0xa8,
	0xdd, 0x24, 0xd7, 0x44, 0xd0, 0x12, 0x29, 0xc0, 0x71, 0x28, 0xda, 0x68, 0x75, 0xb1, 0xa1, 0x17,
	0xf4, 0x0a, 0x29, 0x76, 0x01, 0x76, 0x45, 0x5c, 0x5e, 0xc0, 0x6d, 0xb3, 0x72, 0x9e, 0x92, 0xcb,
	0x13, 0x2e, 0x06, 0x89, 0x91, 0x02, 0x96, 0x63, 0x88, 0x96, 0xd3, 0x44, 0xa8, 0x35, 0x40, 0x5a,
	0xe7, 0xbc, 0x35, 0x3c, 0x5b, 0x41, 0x90, 0xe2, 0xd9, 0x26, 0x64, 0xd4, 0x51, 0xe3, 0xb6, 0xe6,
	0xea, 0xf6, 0xbb, 0x49, 0xfb, 0x5d, 0xfd, 0xb2, 0xa6, 0xfd, 0xee, 0x1e, 0xf7, 0x84, 0xb9, 0xdb,
	0x18, 0xbb, 0xe9, 0x7c, 0xb5, 0x0c, 0xea, 0x28, 0x60, 0x1a, 0x75, 0xf1, 0x7f, 0x50, 0xe9, 0x4e,
	0x0a, 0x69, 0x01, 0x91, 0xd6, 0xe7, 0x22, 0xe9, 0xb4, 0x14, 0xd3, 0x6b, 0x72, 0x15, 0x91, 0x9e,
	0xfb, 0x52, 0xd5, 0xe3, 0x17, 0x49, 0xa7, 0x67, 0x3f, 0x03, 0x25, 0xf9, 0x88, 0x7b, 0x02, 0x33,
	0xf3, 0x0d, 0xfc, 0x4e, 0x94, 0x81, 0xdf, 0xf2, 0x55, 0x79, 0x11, 0x37, 0xf5, 0xc2, 0x79, 0x42,
	0xca, 0xd3, 0xd6, 0xa6, 0xe0, 0x5b, 0xf3, 0x0b, 0x36, 0xa5, 0xd6, 0x7e, 0xe4, 0x49, 0x01, 0x7d,
	0xe8, 0x31, 0x29, 0xea, 0x39, 0xa2, 0xd5, 0xb4, 0x7e, 0x7a, 0x4c, 0x2b, 0xab, 0x33, 0x14, 0x9a,
	0xc1, 0xd9, 0xf8, 0xf4, 0xf3, 0xef, 0xb7, 0x05, 0x87, 0x56, 0x99, 0xee, 0xdb, 0x1d, 0x25, 0xa4,
	0x62, 0x19, 0xbf, 0x14, 0xfa, 0xd9, 0x22, 0x05, 0x64, 0xa2, 0x4e, 0x86, 0xed, 0xc4, 0xf8, 0x56,
	0x6e, 0xcc, 0xd4, 0x98, 0xf0, 0xfb, 0x18, 0x5e, 0xa3, 0x77, 0xcf, 0x0f, 0xc7, 0xf2, 0x59, 0x0f,
	0xdb, 0xde, 0x67, 0x3d, 0x3d, 0xee, 0x7d, 0xfa, 0x91, 0x5c, 0x40, 0xab, 0xad, 0x20, 0xc8, 0xc4,
	0x99, 0x98, 0xde, 0x4c, 0x9c, 0xc9, 0x01, 0x74, 0xd6, 0x11, 0x67, 0x95, 0xae, 0xcc, 0xc1, 0xa1,
	0xdf, 0x2d, 0xb2, 0x34, 0xf6, 0xa0, 0xf4, 0x66, 0x86, 0xfb, 0xf4, 0x2c, 0x55, 0xd6, 0xe6, 0xc9,
	0x0c, 0xc7, 0x36, 0x72, 0x3c, 0xa2, 0x0f, 0xcf, 0xe7, 0x08, 0x7c, 0xa9, 0xf6, 0x9b, 0xf1, 0x3e,
	0xf6, 0x65, 0xd4, 0x9e, 0x64, 0x10, 0xfb, 0xac, 0x87, 0xa3, 0xd7, 0xaf, 0xbf, 0x3a, 0x19, 0xd8,
	0xd6, 0xe9, 0xc0, 0xb6, 0xfe, 0x0c, 0x6c, 0xeb, 0xcb, 0xd0, 0xce, 0x9d, 0x0e, 0xed, 0xdc, 0xaf,
	0xa1, 0x9d, 0x7b, 0xf3, 0xc0, 0xf3, 0x55, 0xc0, 0x9b, 0x6e, 0x1c, 0x74, 0x23, 0x1e, 0xbb, 0x07,
	0xd0, 0x62, 0x5e, 0x87, 0x87, 0x8a, 0x43, 0x76, 0xe4, 0x07, 0x0c, 0x55, 0x71, 0x24, 0x64, 0xb3,
	0x88, 0x7f, 0x8c, 0xf7, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0xb9, 0xfe, 0x6f, 0xce, 0xd7, 0x05,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of Kvzoo items.
	Kvzoo(ctx context.Context, in *QueryGetKvzooRequest, opts ...grpc.CallOption) (*QueryGetKvzooResponse, error)
	KvzooAll(ctx context.Context, in *QueryAllKvzooRequest, opts ...grpc.CallOption) (*QueryAllKvzooResponse, error)
	// Queries a list of ListByOwner items.
	ListByOwner(ctx context.Context, in *QueryListByOwnerRequest, opts ...grpc.CallOption) (*QueryListByOwnerResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/ganymede.zoo.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Kvzoo(ctx context.Context, in *QueryGetKvzooRequest, opts ...grpc.CallOption) (*QueryGetKvzooResponse, error) {
	out := new(QueryGetKvzooResponse)
	err := c.cc.Invoke(ctx, "/ganymede.zoo.Query/Kvzoo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) KvzooAll(ctx context.Context, in *QueryAllKvzooRequest, opts ...grpc.CallOption) (*QueryAllKvzooResponse, error) {
	out := new(QueryAllKvzooResponse)
	err := c.cc.Invoke(ctx, "/ganymede.zoo.Query/KvzooAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListByOwner(ctx context.Context, in *QueryListByOwnerRequest, opts ...grpc.CallOption) (*QueryListByOwnerResponse, error) {
	out := new(QueryListByOwnerResponse)
	err := c.cc.Invoke(ctx, "/ganymede.zoo.Query/ListByOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of Kvzoo items.
	Kvzoo(context.Context, *QueryGetKvzooRequest) (*QueryGetKvzooResponse, error)
	KvzooAll(context.Context, *QueryAllKvzooRequest) (*QueryAllKvzooResponse, error)
	// Queries a list of ListByOwner items.
	ListByOwner(context.Context, *QueryListByOwnerRequest) (*QueryListByOwnerResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Kvzoo(ctx context.Context, req *QueryGetKvzooRequest) (*QueryGetKvzooResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Kvzoo not implemented")
}
func (*UnimplementedQueryServer) KvzooAll(ctx context.Context, req *QueryAllKvzooRequest) (*QueryAllKvzooResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KvzooAll not implemented")
}
func (*UnimplementedQueryServer) ListByOwner(ctx context.Context, req *QueryListByOwnerRequest) (*QueryListByOwnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListByOwner not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ganymede.zoo.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Kvzoo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetKvzooRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Kvzoo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ganymede.zoo.Query/Kvzoo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Kvzoo(ctx, req.(*QueryGetKvzooRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_KvzooAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllKvzooRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).KvzooAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ganymede.zoo.Query/KvzooAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).KvzooAll(ctx, req.(*QueryAllKvzooRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListByOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListByOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListByOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ganymede.zoo.Query/ListByOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListByOwner(ctx, req.(*QueryListByOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ganymede.zoo.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Kvzoo",
			Handler:    _Query_Kvzoo_Handler,
		},
		{
			MethodName: "KvzooAll",
			Handler:    _Query_KvzooAll_Handler,
		},
		{
			MethodName: "ListByOwner",
			Handler:    _Query_ListByOwner_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ganymede/zoo/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetKvzooRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetKvzooRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetKvzooRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ZooKey) > 0 {
		i -= len(m.ZooKey)
		copy(dAtA[i:], m.ZooKey)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ZooKey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetKvzooResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetKvzooResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetKvzooResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Kvzoo.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllKvzooRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllKvzooRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllKvzooRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllKvzooResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllKvzooResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllKvzooResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Kvzoo) > 0 {
		for iNdEx := len(m.Kvzoo) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Kvzoo[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryListByOwnerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListByOwnerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListByOwnerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Limit != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Limit))
		i--
		dAtA[i] = 0x18
	}
	if m.Page != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Page))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListByOwnerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListByOwnerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListByOwnerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Kvzoo) > 0 {
		for iNdEx := len(m.Kvzoo) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Kvzoo[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetKvzooRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.ZooKey)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetKvzooResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Kvzoo.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllKvzooRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllKvzooResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Kvzoo) > 0 {
		for _, e := range m.Kvzoo {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListByOwnerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Page != 0 {
		n += 1 + sovQuery(uint64(m.Page))
	}
	if m.Limit != 0 {
		n += 1 + sovQuery(uint64(m.Limit))
	}
	return n
}

func (m *QueryListByOwnerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Kvzoo) > 0 {
		for _, e := range m.Kvzoo {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetKvzooRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetKvzooRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetKvzooRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZooKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ZooKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetKvzooResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetKvzooResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetKvzooResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Kvzoo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Kvzoo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllKvzooRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllKvzooRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllKvzooRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllKvzooResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllKvzooResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllKvzooResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Kvzoo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Kvzoo = append(m.Kvzoo, Kvzoo{})
			if err := m.Kvzoo[len(m.Kvzoo)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListByOwnerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListByOwnerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListByOwnerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Page", wireType)
			}
			m.Page = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Page |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Limit", wireType)
			}
			m.Limit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Limit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListByOwnerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListByOwnerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListByOwnerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Kvzoo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Kvzoo = append(m.Kvzoo, &Kvzoo{})
			if err := m.Kvzoo[len(m.Kvzoo)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
