// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ganymede/zoo/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateKvzoo struct {
	Creator   string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Owner     string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	ZooKey    string `protobuf:"bytes,3,opt,name=zooKey,proto3" json:"zooKey,omitempty"`
	ZooValue  string `protobuf:"bytes,4,opt,name=zooValue,proto3" json:"zooValue,omitempty"`
	LastDate  string `protobuf:"bytes,5,opt,name=lastDate,proto3" json:"lastDate,omitempty"`
	LinkOwner string `protobuf:"bytes,6,opt,name=linkOwner,proto3" json:"linkOwner,omitempty"`
}

func (m *MsgCreateKvzoo) Reset()         { *m = MsgCreateKvzoo{} }
func (m *MsgCreateKvzoo) String() string { return proto.CompactTextString(m) }
func (*MsgCreateKvzoo) ProtoMessage()    {}
func (*MsgCreateKvzoo) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d35016add5cd7d8, []int{0}
}
func (m *MsgCreateKvzoo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateKvzoo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateKvzoo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateKvzoo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateKvzoo.Merge(m, src)
}
func (m *MsgCreateKvzoo) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateKvzoo) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateKvzoo.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateKvzoo proto.InternalMessageInfo

func (m *MsgCreateKvzoo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateKvzoo) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *MsgCreateKvzoo) GetZooKey() string {
	if m != nil {
		return m.ZooKey
	}
	return ""
}

func (m *MsgCreateKvzoo) GetZooValue() string {
	if m != nil {
		return m.ZooValue
	}
	return ""
}

func (m *MsgCreateKvzoo) GetLastDate() string {
	if m != nil {
		return m.LastDate
	}
	return ""
}

func (m *MsgCreateKvzoo) GetLinkOwner() string {
	if m != nil {
		return m.LinkOwner
	}
	return ""
}

type MsgCreateKvzooResponse struct {
}

func (m *MsgCreateKvzooResponse) Reset()         { *m = MsgCreateKvzooResponse{} }
func (m *MsgCreateKvzooResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateKvzooResponse) ProtoMessage()    {}
func (*MsgCreateKvzooResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d35016add5cd7d8, []int{1}
}
func (m *MsgCreateKvzooResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateKvzooResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateKvzooResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateKvzooResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateKvzooResponse.Merge(m, src)
}
func (m *MsgCreateKvzooResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateKvzooResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateKvzooResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateKvzooResponse proto.InternalMessageInfo

type MsgUpdateKvzoo struct {
	Creator   string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Owner     string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	ZooKey    string `protobuf:"bytes,3,opt,name=zooKey,proto3" json:"zooKey,omitempty"`
	ZooValue  string `protobuf:"bytes,4,opt,name=zooValue,proto3" json:"zooValue,omitempty"`
	LastDate  string `protobuf:"bytes,5,opt,name=lastDate,proto3" json:"lastDate,omitempty"`
	LinkOwner string `protobuf:"bytes,6,opt,name=linkOwner,proto3" json:"linkOwner,omitempty"`
}

func (m *MsgUpdateKvzoo) Reset()         { *m = MsgUpdateKvzoo{} }
func (m *MsgUpdateKvzoo) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateKvzoo) ProtoMessage()    {}
func (*MsgUpdateKvzoo) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d35016add5cd7d8, []int{2}
}
func (m *MsgUpdateKvzoo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateKvzoo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateKvzoo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateKvzoo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateKvzoo.Merge(m, src)
}
func (m *MsgUpdateKvzoo) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateKvzoo) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateKvzoo.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateKvzoo proto.InternalMessageInfo

func (m *MsgUpdateKvzoo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdateKvzoo) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *MsgUpdateKvzoo) GetZooKey() string {
	if m != nil {
		return m.ZooKey
	}
	return ""
}

func (m *MsgUpdateKvzoo) GetZooValue() string {
	if m != nil {
		return m.ZooValue
	}
	return ""
}

func (m *MsgUpdateKvzoo) GetLastDate() string {
	if m != nil {
		return m.LastDate
	}
	return ""
}

func (m *MsgUpdateKvzoo) GetLinkOwner() string {
	if m != nil {
		return m.LinkOwner
	}
	return ""
}

type MsgUpdateKvzooResponse struct {
}

func (m *MsgUpdateKvzooResponse) Reset()         { *m = MsgUpdateKvzooResponse{} }
func (m *MsgUpdateKvzooResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateKvzooResponse) ProtoMessage()    {}
func (*MsgUpdateKvzooResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d35016add5cd7d8, []int{3}
}
func (m *MsgUpdateKvzooResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateKvzooResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateKvzooResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateKvzooResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateKvzooResponse.Merge(m, src)
}
func (m *MsgUpdateKvzooResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateKvzooResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateKvzooResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateKvzooResponse proto.InternalMessageInfo

type MsgDeleteKvzoo struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Owner   string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	ZooKey  string `protobuf:"bytes,3,opt,name=zooKey,proto3" json:"zooKey,omitempty"`
}

func (m *MsgDeleteKvzoo) Reset()         { *m = MsgDeleteKvzoo{} }
func (m *MsgDeleteKvzoo) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteKvzoo) ProtoMessage()    {}
func (*MsgDeleteKvzoo) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d35016add5cd7d8, []int{4}
}
func (m *MsgDeleteKvzoo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteKvzoo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteKvzoo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteKvzoo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteKvzoo.Merge(m, src)
}
func (m *MsgDeleteKvzoo) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteKvzoo) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteKvzoo.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteKvzoo proto.InternalMessageInfo

func (m *MsgDeleteKvzoo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgDeleteKvzoo) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *MsgDeleteKvzoo) GetZooKey() string {
	if m != nil {
		return m.ZooKey
	}
	return ""
}

type MsgDeleteKvzooResponse struct {
}

func (m *MsgDeleteKvzooResponse) Reset()         { *m = MsgDeleteKvzooResponse{} }
func (m *MsgDeleteKvzooResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteKvzooResponse) ProtoMessage()    {}
func (*MsgDeleteKvzooResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d35016add5cd7d8, []int{5}
}
func (m *MsgDeleteKvzooResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteKvzooResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteKvzooResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteKvzooResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteKvzooResponse.Merge(m, src)
}
func (m *MsgDeleteKvzooResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteKvzooResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteKvzooResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteKvzooResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateKvzoo)(nil), "ganymede.zoo.MsgCreateKvzoo")
	proto.RegisterType((*MsgCreateKvzooResponse)(nil), "ganymede.zoo.MsgCreateKvzooResponse")
	proto.RegisterType((*MsgUpdateKvzoo)(nil), "ganymede.zoo.MsgUpdateKvzoo")
	proto.RegisterType((*MsgUpdateKvzooResponse)(nil), "ganymede.zoo.MsgUpdateKvzooResponse")
	proto.RegisterType((*MsgDeleteKvzoo)(nil), "ganymede.zoo.MsgDeleteKvzoo")
	proto.RegisterType((*MsgDeleteKvzooResponse)(nil), "ganymede.zoo.MsgDeleteKvzooResponse")
}

func init() { proto.RegisterFile("ganymede/zoo/tx.proto", fileDescriptor_6d35016add5cd7d8) }

var fileDescriptor_6d35016add5cd7d8 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x93, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x86, 0x59, 0x11, 0x94, 0xd5, 0x78, 0xd8, 0x28, 0xd9, 0x10, 0xd2, 0x18, 0xe2, 0xc1, 0x8b,
	0x6d, 0xa2, 0x37, 0x8f, 0xca, 0x8d, 0x10, 0x23, 0x51, 0x63, 0xbc, 0x2d, 0x30, 0x69, 0x08, 0xa5,
	0xd3, 0x74, 0x17, 0xa5, 0x7d, 0x0a, 0x9f, 0xc4, 0xe7, 0xf0, 0xc8, 0xd1, 0xa3, 0x81, 0xf7, 0x30,
	0xa6, 0x5b, 0x8a, 0xdb, 0xd0, 0x78, 0xf2, 0xe2, 0xf1, 0x9f, 0x7f, 0xf3, 0xcd, 0xfe, 0xb3, 0x3b,
	0xf4, 0xc8, 0x15, 0x7e, 0x34, 0x81, 0x21, 0x38, 0x31, 0xa2, 0xa3, 0x66, 0x76, 0x10, 0xa2, 0x42,
	0xb6, 0x9f, 0x95, 0xed, 0x18, 0xb1, 0xc1, 0x73, 0x87, 0xc6, 0xcf, 0x31, 0x62, 0x7a, 0xae, 0xf5,
	0x46, 0xe8, 0x41, 0x57, 0xba, 0xd7, 0x21, 0x08, 0x05, 0x9d, 0xc4, 0x60, 0x9c, 0xee, 0x0c, 0x12,
	0x89, 0x21, 0x27, 0xc7, 0xe4, 0xb4, 0xd6, 0xcb, 0x24, 0x3b, 0xa4, 0x15, 0x7c, 0xf1, 0x21, 0xe4,
	0x5b, 0xba, 0x9e, 0x0a, 0x56, 0xa7, 0xd5, 0x18, 0xb1, 0x03, 0x11, 0x2f, 0xeb, 0xf2, 0x4a, 0xb1,
	0x06, 0xdd, 0x8d, 0x11, 0x1f, 0x84, 0x37, 0x05, 0xbe, 0xad, 0x9d, 0xb5, 0x4e, 0x3c, 0x4f, 0x48,
	0xd5, 0x16, 0x0a, 0x78, 0x25, 0xf5, 0x32, 0xcd, 0x9a, 0xb4, 0xe6, 0x8d, 0xfc, 0xf1, 0x8d, 0xee,
	0x54, 0xd5, 0xe6, 0x4f, 0xa1, 0xc5, 0x69, 0x3d, 0x7f, 0xdf, 0x1e, 0xc8, 0x00, 0x7d, 0x09, 0x59,
	0x94, 0xfb, 0x60, 0xf8, 0xaf, 0xa2, 0x18, 0xf7, 0x5d, 0x47, 0x79, 0xd4, 0x49, 0xda, 0xe0, 0xc1,
	0x1f, 0x27, 0x59, 0xf5, 0x34, 0xc8, 0x59, 0xcf, 0xf3, 0x2f, 0x42, 0xcb, 0x5d, 0xe9, 0xb2, 0x5b,
	0xba, 0x67, 0xfe, 0x86, 0xa6, 0x6d, 0xfe, 0x24, 0x3b, 0x3f, 0xfb, 0xc6, 0xc9, 0x6f, 0x6e, 0x86,
	0x4e, 0x90, 0xe6, 0xab, 0x6c, 0x22, 0x0d, 0xb7, 0x00, 0x59, 0x30, 0xa1, 0x04, 0x69, 0x8e, 0x67,
	0x13, 0x69, 0xb8, 0x05, 0xc8, 0x82, 0x01, 0x5c, 0xdd, 0xbd, 0x2f, 0x2c, 0x32, 0x5f, 0x58, 0xe4,
	0x73, 0x61, 0x91, 0xd7, 0xa5, 0x55, 0x9a, 0x2f, 0xad, 0xd2, 0xc7, 0xd2, 0x2a, 0x3d, 0x5d, 0xba,
	0x23, 0xe5, 0x89, 0xbe, 0x1d, 0x79, 0x71, 0x20, 0x22, 0x7b, 0x80, 0x13, 0xc7, 0x9d, 0x0a, 0x5f,
	0x09, 0x74, 0x06, 0x28, 0x27, 0x28, 0xcf, 0x14, 0x48, 0xe5, 0xac, 0x97, 0x6c, 0x96, 0xee, 0x62,
	0x14, 0x80, 0xec, 0x57, 0xf5, 0x9e, 0x5d, 0x7c, 0x07, 0x00, 0x00, 0xff, 0xff, 0x76, 0xba, 0xea,
	0xfe, 0xa8, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreateKvzoo(ctx context.Context, in *MsgCreateKvzoo, opts ...grpc.CallOption) (*MsgCreateKvzooResponse, error)
	UpdateKvzoo(ctx context.Context, in *MsgUpdateKvzoo, opts ...grpc.CallOption) (*MsgUpdateKvzooResponse, error)
	DeleteKvzoo(ctx context.Context, in *MsgDeleteKvzoo, opts ...grpc.CallOption) (*MsgDeleteKvzooResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateKvzoo(ctx context.Context, in *MsgCreateKvzoo, opts ...grpc.CallOption) (*MsgCreateKvzooResponse, error) {
	out := new(MsgCreateKvzooResponse)
	err := c.cc.Invoke(ctx, "/ganymede.zoo.Msg/CreateKvzoo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateKvzoo(ctx context.Context, in *MsgUpdateKvzoo, opts ...grpc.CallOption) (*MsgUpdateKvzooResponse, error) {
	out := new(MsgUpdateKvzooResponse)
	err := c.cc.Invoke(ctx, "/ganymede.zoo.Msg/UpdateKvzoo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteKvzoo(ctx context.Context, in *MsgDeleteKvzoo, opts ...grpc.CallOption) (*MsgDeleteKvzooResponse, error) {
	out := new(MsgDeleteKvzooResponse)
	err := c.cc.Invoke(ctx, "/ganymede.zoo.Msg/DeleteKvzoo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreateKvzoo(context.Context, *MsgCreateKvzoo) (*MsgCreateKvzooResponse, error)
	UpdateKvzoo(context.Context, *MsgUpdateKvzoo) (*MsgUpdateKvzooResponse, error)
	DeleteKvzoo(context.Context, *MsgDeleteKvzoo) (*MsgDeleteKvzooResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateKvzoo(ctx context.Context, req *MsgCreateKvzoo) (*MsgCreateKvzooResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateKvzoo not implemented")
}
func (*UnimplementedMsgServer) UpdateKvzoo(ctx context.Context, req *MsgUpdateKvzoo) (*MsgUpdateKvzooResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateKvzoo not implemented")
}
func (*UnimplementedMsgServer) DeleteKvzoo(ctx context.Context, req *MsgDeleteKvzoo) (*MsgDeleteKvzooResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteKvzoo not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateKvzoo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateKvzoo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateKvzoo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ganymede.zoo.Msg/CreateKvzoo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateKvzoo(ctx, req.(*MsgCreateKvzoo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateKvzoo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateKvzoo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateKvzoo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ganymede.zoo.Msg/UpdateKvzoo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateKvzoo(ctx, req.(*MsgUpdateKvzoo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteKvzoo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteKvzoo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteKvzoo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ganymede.zoo.Msg/DeleteKvzoo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteKvzoo(ctx, req.(*MsgDeleteKvzoo))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ganymede.zoo.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateKvzoo",
			Handler:    _Msg_CreateKvzoo_Handler,
		},
		{
			MethodName: "UpdateKvzoo",
			Handler:    _Msg_UpdateKvzoo_Handler,
		},
		{
			MethodName: "DeleteKvzoo",
			Handler:    _Msg_DeleteKvzoo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ganymede/zoo/tx.proto",
}

func (m *MsgCreateKvzoo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateKvzoo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateKvzoo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.LinkOwner) > 0 {
		i -= len(m.LinkOwner)
		copy(dAtA[i:], m.LinkOwner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.LinkOwner)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.LastDate) > 0 {
		i -= len(m.LastDate)
		copy(dAtA[i:], m.LastDate)
		i = encodeVarintTx(dAtA, i, uint64(len(m.LastDate)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ZooValue) > 0 {
		i -= len(m.ZooValue)
		copy(dAtA[i:], m.ZooValue)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ZooValue)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ZooKey) > 0 {
		i -= len(m.ZooKey)
		copy(dAtA[i:], m.ZooKey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ZooKey)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateKvzooResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateKvzooResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateKvzooResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateKvzoo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateKvzoo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateKvzoo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.LinkOwner) > 0 {
		i -= len(m.LinkOwner)
		copy(dAtA[i:], m.LinkOwner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.LinkOwner)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.LastDate) > 0 {
		i -= len(m.LastDate)
		copy(dAtA[i:], m.LastDate)
		i = encodeVarintTx(dAtA, i, uint64(len(m.LastDate)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ZooValue) > 0 {
		i -= len(m.ZooValue)
		copy(dAtA[i:], m.ZooValue)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ZooValue)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ZooKey) > 0 {
		i -= len(m.ZooKey)
		copy(dAtA[i:], m.ZooKey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ZooKey)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateKvzooResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateKvzooResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateKvzooResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDeleteKvzoo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteKvzoo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteKvzoo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ZooKey) > 0 {
		i -= len(m.ZooKey)
		copy(dAtA[i:], m.ZooKey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ZooKey)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteKvzooResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteKvzooResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteKvzooResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateKvzoo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ZooKey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ZooValue)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.LastDate)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.LinkOwner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateKvzooResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateKvzoo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ZooKey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ZooValue)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.LastDate)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.LinkOwner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateKvzooResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDeleteKvzoo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ZooKey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDeleteKvzooResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateKvzoo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateKvzoo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateKvzoo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZooKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ZooKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZooValue", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ZooValue = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastDate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastDate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LinkOwner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LinkOwner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateKvzooResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateKvzooResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateKvzooResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateKvzoo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateKvzoo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateKvzoo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZooKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ZooKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZooValue", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ZooValue = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastDate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastDate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LinkOwner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LinkOwner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateKvzooResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateKvzooResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateKvzooResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteKvzoo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteKvzoo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteKvzoo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZooKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ZooKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteKvzooResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteKvzooResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteKvzooResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
