// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ganymede/postoffice/sent_post.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SentPost struct {
	Id           uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PostID       string `protobuf:"bytes,2,opt,name=postID,proto3" json:"postID,omitempty"`
	Title        string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Payload      string `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	ToChain      string `protobuf:"bytes,5,opt,name=toChain,proto3" json:"toChain,omitempty"`
	Sender       string `protobuf:"bytes,6,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver     string `protobuf:"bytes,7,opt,name=receiver,proto3" json:"receiver,omitempty"`
	SentDate     string `protobuf:"bytes,8,opt,name=sentDate,proto3" json:"sentDate,omitempty"`
	LinkSender   string `protobuf:"bytes,9,opt,name=linkSender,proto3" json:"linkSender,omitempty"`
	LinkReceiver string `protobuf:"bytes,10,opt,name=linkReceiver,proto3" json:"linkReceiver,omitempty"`
}

func (m *SentPost) Reset()         { *m = SentPost{} }
func (m *SentPost) String() string { return proto.CompactTextString(m) }
func (*SentPost) ProtoMessage()    {}
func (*SentPost) Descriptor() ([]byte, []int) {
	return fileDescriptor_37cb895d75e3a95f, []int{0}
}
func (m *SentPost) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SentPost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SentPost.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SentPost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SentPost.Merge(m, src)
}
func (m *SentPost) XXX_Size() int {
	return m.Size()
}
func (m *SentPost) XXX_DiscardUnknown() {
	xxx_messageInfo_SentPost.DiscardUnknown(m)
}

var xxx_messageInfo_SentPost proto.InternalMessageInfo

func (m *SentPost) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SentPost) GetPostID() string {
	if m != nil {
		return m.PostID
	}
	return ""
}

func (m *SentPost) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SentPost) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func (m *SentPost) GetToChain() string {
	if m != nil {
		return m.ToChain
	}
	return ""
}

func (m *SentPost) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *SentPost) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *SentPost) GetSentDate() string {
	if m != nil {
		return m.SentDate
	}
	return ""
}

func (m *SentPost) GetLinkSender() string {
	if m != nil {
		return m.LinkSender
	}
	return ""
}

func (m *SentPost) GetLinkReceiver() string {
	if m != nil {
		return m.LinkReceiver
	}
	return ""
}

func init() {
	proto.RegisterType((*SentPost)(nil), "ganymede.postoffice.SentPost")
}

func init() {
	proto.RegisterFile("ganymede/postoffice/sent_post.proto", fileDescriptor_37cb895d75e3a95f)
}

var fileDescriptor_37cb895d75e3a95f = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0xeb, 0xd0, 0x5f, 0x0b, 0x31, 0x18, 0x84, 0x2c, 0x06, 0xab, 0x2a, 0x4b, 0x17, 0x92,
	0x81, 0x27, 0x00, 0xba, 0xb0, 0xa1, 0x76, 0x83, 0x01, 0xb9, 0xc9, 0x6d, 0xb1, 0x48, 0xed, 0x28,
	0xbe, 0x20, 0xc2, 0x53, 0xf4, 0xb1, 0x18, 0x3b, 0x32, 0xa2, 0xe6, 0x45, 0x90, 0xed, 0xa6, 0x94,
	0xf1, 0x3b, 0xdf, 0x91, 0xaf, 0xac, 0x43, 0x2f, 0x97, 0x52, 0x57, 0x2b, 0xc8, 0x20, 0x29, 0x8c,
	0x45, 0xb3, 0x58, 0xa8, 0x14, 0x12, 0x0b, 0x1a, 0x9f, 0x1d, 0xc7, 0x45, 0x69, 0xd0, 0xb0, 0xd3,
	0xa6, 0x14, 0xff, 0x95, 0x46, 0xeb, 0x88, 0xf6, 0x67, 0xa0, 0xf1, 0xc1, 0x58, 0x64, 0x27, 0x34,
	0x52, 0x19, 0x27, 0x43, 0x32, 0x6e, 0x4f, 0x23, 0x95, 0xb1, 0x73, 0xda, 0x75, 0xd5, 0xfb, 0x09,
	0x8f, 0x86, 0x64, 0x3c, 0x98, 0xee, 0x88, 0x9d, 0xd1, 0x0e, 0x2a, 0xcc, 0x81, 0x1f, 0xf9, 0x38,
	0x00, 0xe3, 0xb4, 0x57, 0xc8, 0x2a, 0x37, 0x32, 0xe3, 0x6d, 0x9f, 0x37, 0xe8, 0x0c, 0x9a, 0xbb,
	0x17, 0xa9, 0x34, 0xef, 0x04, 0xb3, 0x43, 0x77, 0xc1, 0x82, 0xce, 0xa0, 0xe4, 0xdd, 0x70, 0x21,
	0x10, 0xbb, 0xa0, 0xfd, 0x12, 0x52, 0x50, 0xef, 0x50, 0xf2, 0x9e, 0x37, 0x7b, 0x76, 0xce, 0x7d,
	0x6d, 0x22, 0x11, 0x78, 0x3f, 0xb8, 0x86, 0x99, 0xa0, 0x34, 0x57, 0xfa, 0x75, 0x16, 0xde, 0x1c,
	0x78, 0x7b, 0x90, 0xb0, 0x11, 0x3d, 0x76, 0x34, 0x6d, 0xde, 0xa6, 0xbe, 0xf1, 0x2f, 0xbb, 0x7d,
	0xfa, 0xda, 0x0a, 0xb2, 0xd9, 0x0a, 0xf2, 0xb3, 0x15, 0x64, 0x5d, 0x8b, 0xd6, 0xa6, 0x16, 0xad,
	0xef, 0x5a, 0xb4, 0x1e, 0x6f, 0x96, 0x0a, 0x73, 0x39, 0x8f, 0xab, 0xfc, 0xb3, 0x90, 0x55, 0x9c,
	0x9a, 0x55, 0xb2, 0x7c, 0x93, 0x1a, 0xa5, 0x49, 0x52, 0x63, 0x57, 0xc6, 0x5e, 0x21, 0x58, 0x4c,
	0xf6, 0x63, 0x7c, 0x1c, 0xce, 0x81, 0x55, 0x01, 0x76, 0xde, 0xf5, 0x5b, 0x5c, 0xff, 0x06, 0x00,
	0x00, 0xff, 0xff, 0x07, 0x5f, 0xd4, 0x7b, 0xb2, 0x01, 0x00, 0x00,
}

func (m *SentPost) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SentPost) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SentPost) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.LinkReceiver) > 0 {
		i -= len(m.LinkReceiver)
		copy(dAtA[i:], m.LinkReceiver)
		i = encodeVarintSentPost(dAtA, i, uint64(len(m.LinkReceiver)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.LinkSender) > 0 {
		i -= len(m.LinkSender)
		copy(dAtA[i:], m.LinkSender)
		i = encodeVarintSentPost(dAtA, i, uint64(len(m.LinkSender)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.SentDate) > 0 {
		i -= len(m.SentDate)
		copy(dAtA[i:], m.SentDate)
		i = encodeVarintSentPost(dAtA, i, uint64(len(m.SentDate)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Receiver) > 0 {
		i -= len(m.Receiver)
		copy(dAtA[i:], m.Receiver)
		i = encodeVarintSentPost(dAtA, i, uint64(len(m.Receiver)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintSentPost(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.ToChain) > 0 {
		i -= len(m.ToChain)
		copy(dAtA[i:], m.ToChain)
		i = encodeVarintSentPost(dAtA, i, uint64(len(m.ToChain)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Payload) > 0 {
		i -= len(m.Payload)
		copy(dAtA[i:], m.Payload)
		i = encodeVarintSentPost(dAtA, i, uint64(len(m.Payload)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintSentPost(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.PostID) > 0 {
		i -= len(m.PostID)
		copy(dAtA[i:], m.PostID)
		i = encodeVarintSentPost(dAtA, i, uint64(len(m.PostID)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintSentPost(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintSentPost(dAtA []byte, offset int, v uint64) int {
	offset -= sovSentPost(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SentPost) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovSentPost(uint64(m.Id))
	}
	l = len(m.PostID)
	if l > 0 {
		n += 1 + l + sovSentPost(uint64(l))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovSentPost(uint64(l))
	}
	l = len(m.Payload)
	if l > 0 {
		n += 1 + l + sovSentPost(uint64(l))
	}
	l = len(m.ToChain)
	if l > 0 {
		n += 1 + l + sovSentPost(uint64(l))
	}
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovSentPost(uint64(l))
	}
	l = len(m.Receiver)
	if l > 0 {
		n += 1 + l + sovSentPost(uint64(l))
	}
	l = len(m.SentDate)
	if l > 0 {
		n += 1 + l + sovSentPost(uint64(l))
	}
	l = len(m.LinkSender)
	if l > 0 {
		n += 1 + l + sovSentPost(uint64(l))
	}
	l = len(m.LinkReceiver)
	if l > 0 {
		n += 1 + l + sovSentPost(uint64(l))
	}
	return n
}

func sovSentPost(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSentPost(x uint64) (n int) {
	return sovSentPost(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SentPost) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSentPost
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SentPost: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SentPost: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSentPost
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PostID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSentPost
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSentPost
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSentPost
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PostID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSentPost
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSentPost
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSentPost
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payload", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSentPost
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSentPost
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSentPost
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payload = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToChain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSentPost
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSentPost
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSentPost
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ToChain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSentPost
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSentPost
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSentPost
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Receiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSentPost
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSentPost
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSentPost
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Receiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SentDate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSentPost
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSentPost
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSentPost
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SentDate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LinkSender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSentPost
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSentPost
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSentPost
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LinkSender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LinkReceiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSentPost
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSentPost
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSentPost
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LinkReceiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSentPost(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSentPost
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSentPost(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSentPost
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSentPost
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSentPost
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSentPost
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSentPost
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSentPost
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSentPost        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSentPost          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSentPost = fmt.Errorf("proto: unexpected end of group")
)
